version: "2"

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - "DEBUG=false"

      - "DB_USER=tomwieland_nl_user"
      - "DB_PASS=tomwieland_nl_password"
      - "PG_PASSWORD=postgres"
      - "DB_NAME=tomwieland_nl_develop"
      - "DB_TEMPLATE="

      - "DB_EXTENSION="

      - "REPLICATION_MODE="
      - "REPLICATION_USER="
      - "REPLICATION_PASS="
      - "REPLICATION_SSLMODE="

    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql

  app:
    depends_on:
      - "postgresql"
    build:
      context: "./services/app"
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=develop"
      - "DB_HOST=postgresql"
      - "DB_PORT=5432"
      - "DB_USER=tomwieland_nl_user"
      - "DB_PASS=tomwieland_nl_password"
      - "DB_NAME=tomwieland_nl_develop"
    volumes:
      - "./services/app:/service"
      #- "/service/node_modules"
