version: "2"

services:
  # zookeeper:
  #   image: "wurstmeister/zookeeper"
  #   ports:
  #     - "2181:2181"
  #
  # kafka1:
  #   build:
  #     context: "./services/kafka"
  #     dockerfile: "Dockerfile1"
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: "0.0.0.0"
  #     KAFKA_CREATE_TOPICS: "test:1:1"
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  # kafka2:
  #   build:
  #     context: "./services/kafka"
  #     dockerfile: "Dockerfile2"
  #   ports:
  #     - "9093:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: "0.0.0.0"
  #     KAFKA_CREATE_TOPICS: "test:1:3"
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #
  # kafka3:
  #   build:
  #     context: "./services/kafka"
  #     dockerfile: "Dockerfile3"
  #   ports:
  #     - "9094:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: "0.0.0.0"
  #     KAFKA_CREATE_TOPICS: "test:1:3"
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  # users:
  #   build:
  #     context: "./services/users"
  #     dockerfile: "Dockerfile"
  #   ports:
  #     - "4001:4001"
  #   environment:
  #     NODE_ENV: "develop"
  #     # KAFKA_BROKER_LIST: "kafka1:9092,kafka2:9093,kafka3:9094"
  #     KAFKA_BROKER_LIST: "kafka1:9092"
  #   volumes:
  #     - "./services/users:/service"

  postgresql:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=tomwieland_nl_user"
      - "POSTGRES_PASSWORD=tomwieland_nl_password"
      - "POSTGRES_DB=tomwieland_nl_develop"
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql

  app:
    depends_on:
      - "postgresql"
    build:
      context: "./services/app"
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "develop"
      DB_HOST: "postgresql"
      DB_PORT: "5432"
      DB_USER: "tomwieland_nl_user"
      DB_PASS: "tomwieland_nl_password"
      DB_NAME: "tomwieland_nl_develop"
    volumes:
      - "./services/app:/service"
      - "/service/node_modules"
