version: "2"

services:
  db:
    container_name: "db"
    hostname: "db"
    image: "mongo"
    volumes:
      - "../../volumes/mongodb:/data/db"
    ports:
      - "27017:27017"

  tomwielandnl-app:
    container_name: "app"
    image: "app"
    depends_on:
      - "db"
    build:
      context: "./services/app"
      dockerfile: "docker/Dockerfile-develop"
    ports:
      - "3000:3000"
      - "3123:3123"
      - "8080:8080"
    volumes:
      - "./services/app:/src/"
