version: "2"

services:
  db:
    image: "mongo"
    hostname: "db"
    volumes:
      - "./volumes/mongodb:/data/db"
    ports:
      - "27017:27017"

  app:
    depends_on:
      - "db"
    build:
      context: "./services/app"
      dockerfile: "Dockerfile-production"
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=production"
    volumes:
      - "./services/app:/service"
    #  - "/service/node_modules"

  triple_store:
    build: "./services/triple-store"
    ports:
      - "4001:4001"
    environment:
      - "LOGLEVEL=DEBUG"
      - "DBPATH=/db"
      - "PORT=4001"
    volumes:
      - "./services/triple-store:/service"
      - "./.triple-store:/db"
    #  - "/service/node_modules"
