# Use the latest nodejs version.
FROM node:latest

# Port for the application.
EXPOSE 3000

# Websocket for Hot Module Reloading. Probably want to disable this in production.
EXPOSE 3123

# Create the application directory in the dock.
RUN mkdir /src

# Add all the files to the container.
ADD . /src/

# Change the working directory.
WORKDIR /src

# Install all the dependencies.
RUN npm install

# Run the app.
CMD node_modules/.bin/gulp develop
